# Generated by Django 5.2.9 on 2026-01-01 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cprn_number",
                    models.CharField(
                        blank=True,
                        help_text="Customer Presentment Registration Number from Bill Bitts",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "web3_wallet_address",
                    models.CharField(
                        blank=True,
                        help_text="Ethereum wallet address for ERC-1400 security token transactions",
                        max_length=42,
                    ),
                ),
                (
                    "neo_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Current balance from NEO Bank PSP",
                        max_digits=20,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the payment profile has been verified",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Profile",
                "verbose_name_plural": "Payment Profiles",
                "db_table": "payment_profiles",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        help_text="Transaction ID from NEO Bank/Bill Bitts",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("SETTLED", "Settled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "token_contract_address",
                    models.CharField(
                        blank=True,
                        help_text="ERC-1400 token contract address",
                        max_length=42,
                    ),
                ),
                (
                    "token_symbol",
                    models.CharField(
                        blank=True,
                        help_text="Symbol of the ERC-1400 security token (e.g., DPO-STO)",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("webhook_payload", models.JSONField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="payments.paymentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "db_table": "payment_transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="paymentprofile",
            index=models.Index(
                fields=["cprn_number"], name="payment_pro_cprn_nu_40c29c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentprofile",
            index=models.Index(
                fields=["web3_wallet_address"], name="payment_pro_web3_wa_22e4e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["transaction_id"], name="payment_tra_transac_4a22d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["status"], name="payment_tra_status_137fde_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["-created_at"], name="payment_tra_created_94cd0f_idx"
            ),
        ),
    ]
