# Generated by Django 5.2.9 on 2026-01-02 04:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Issuer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        db_index=True, help_text="Legal entity name", max_length=255
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier", max_length=255, unique=True
                    ),
                ),
                (
                    "logo",
                    models.URLField(
                        blank=True, help_text="Company logo URL", null=True
                    ),
                ),
                (
                    "security_name",
                    models.CharField(
                        help_text="Name of the security being offered", max_length=255
                    ),
                ),
                (
                    "isin",
                    models.CharField(
                        db_index=True,
                        help_text="ISIN (International Securities Identification Number)",
                        max_length=12,
                        unique=True,
                    ),
                ),
                (
                    "price_per_token",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "total_offering",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "min_investment",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "linkedin",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "twitter",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "youtube",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "facebook",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "instagram",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "paypal_account",
                    models.CharField(
                        blank=True,
                        help_text="PayPal username or email",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "wire_bank_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "wire_account_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "wire_routing_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "wire_swift",
                    models.CharField(
                        blank=True, help_text="SWIFT/BIC code", max_length=11, null=True
                    ),
                ),
                (
                    "crypto_merchant_id",
                    models.CharField(
                        blank=True,
                        help_text="BillBitcoins merchant ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "doc_prospectus",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "doc_terms",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "doc_risks",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "doc_subscription",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Company/offering description", null=True
                    ),
                ),
                (
                    "sec_form_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Complete SEC form data from BD",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Pending Review"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("closed", "Closed"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "offering_page_url",
                    models.URLField(
                        blank=True,
                        help_text="Full URL to white-labeled offering page",
                        null=True,
                    ),
                ),
                (
                    "bd_post_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Brilliant Directories post/listing ID",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, help_text="When offering went live", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal admin notes", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Issuer",
                "verbose_name_plural": "Issuers",
                "db_table": "issuers",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company_name", "status"],
                        name="issuers_company_5ee1ff_idx",
                    ),
                    models.Index(
                        fields=["isin", "status"], name="issuers_isin_58f966_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="issuers_created_9b5021_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="IssuerDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("form_d", "SEC Form D"),
                            ("form_c", "SEC Form C"),
                            ("form_1a", "SEC Form 1-A"),
                            ("form_10", "SEC Form 10"),
                            ("ppm", "Private Placement Memorandum"),
                            ("subscription", "Subscription Agreement"),
                            ("terms", "Terms & Conditions"),
                            ("risks", "Risk Disclosures"),
                        ],
                        max_length=20,
                    ),
                ),
                ("template_version", models.CharField(default="1.0", max_length=50)),
                (
                    "file_url",
                    models.URLField(help_text="Adobe Cloud or S3 URL to generated PDF"),
                ),
                (
                    "file_hash",
                    models.CharField(
                        help_text="SHA256 hash for integrity verification",
                        max_length=64,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("generated_by", models.CharField(default="system", max_length=255)),
                (
                    "generation_data",
                    models.JSONField(
                        default=dict, help_text="Data used to generate document"
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=True, help_text="Is this the current version?"
                    ),
                ),
                (
                    "issuer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="issuers.issuer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Issuer Document",
                "verbose_name_plural": "Issuer Documents",
                "db_table": "issuer_documents",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["issuer", "document_type", "is_current"],
                        name="issuer_docu_issuer__46fc22_idx",
                    )
                ],
            },
        ),
    ]
