# Generated by Django 5.2.9 on 2026-01-02 05:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issuers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("source_name", models.CharField(max_length=100, unique=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("MODEL", "Django Model"),
                            ("API", "External API"),
                            ("COMPUTED", "Computed/Calculated"),
                            ("USER_INPUT", "User Input Required"),
                            ("CONSTANT", "Constant Value"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True, help_text="e.g., 'Issuer'", max_length=100
                    ),
                ),
                (
                    "model_path",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'apps.issuers.models.Issuer'",
                        max_length=255,
                    ),
                ),
                ("api_endpoint", models.URLField(blank=True)),
                (
                    "api_method",
                    models.CharField(blank=True, default="GET", max_length=10),
                ),
                ("api_headers", models.JSONField(blank=True, default=dict)),
                (
                    "computation_function",
                    models.CharField(
                        blank=True, help_text="Python function path", max_length=255
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Data Source",
                "verbose_name_plural": "Data Sources",
                "db_table": "sec_data_sources",
            },
        ),
        migrations.CreateModel(
            name="SECFormType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("FORM_D", "SEC Form D (Reg D)"),
                            ("FORM_C", "SEC Form C (Reg CF)"),
                            ("FORM_1A", "SEC Form 1-A (Reg A)"),
                            ("FORM_10", "SEC Form 10"),
                            ("PPM", "Private Placement Memorandum"),
                            ("SUBSCRIPTION", "Subscription Agreement"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "SEC Form Type",
                "verbose_name_plural": "SEC Form Types",
                "db_table": "sec_form_types",
            },
        ),
        migrations.CreateModel(
            name="FieldDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("field_name", models.CharField(max_length=100)),
                ("display_name", models.CharField(max_length=255)),
                ("field_path", models.CharField(max_length=500)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("STRING", "String/Text"),
                            ("INTEGER", "Integer"),
                            ("DECIMAL", "Decimal/Float"),
                            ("BOOLEAN", "Boolean"),
                            ("DATE", "Date"),
                            ("DATETIME", "Date & Time"),
                            ("CURRENCY", "Currency"),
                            ("PERCENTAGE", "Percentage"),
                            ("ADDRESS", "Address"),
                            ("EMAIL", "Email"),
                            ("PHONE", "Phone Number"),
                            ("URL", "URL"),
                            ("ARRAY", "Array/List"),
                            ("OBJECT", "Object/Dictionary"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("default_value", models.CharField(blank=True, max_length=500)),
                ("validation_regex", models.CharField(blank=True, max_length=500)),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("min_length", models.IntegerField(blank=True, null=True)),
                ("max_length", models.IntegerField(blank=True, null=True)),
                (
                    "allowed_values_json",
                    models.JSONField(
                        blank=True, default=list, help_text="Array of allowed values"
                    ),
                ),
                (
                    "format_template",
                    models.CharField(
                        blank=True,
                        help_text="e.g., '${:,.2f}' for currency",
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("help_text", models.TextField(blank=True)),
                ("example_value", models.CharField(blank=True, max_length=500)),
                (
                    "aliases_json",
                    models.JSONField(
                        blank=True, default=list, help_text="Alternative names"
                    ),
                ),
                (
                    "tags_json",
                    models.JSONField(
                        blank=True, default=list, help_text="Tags for categorization"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="issuers.datasource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Definition",
                "verbose_name_plural": "Field Definitions",
                "db_table": "sec_field_definitions",
                "ordering": ["data_source", "field_name"],
                "unique_together": {("data_source", "field_name")},
            },
        ),
        migrations.CreateModel(
            name="SECDocumentTemplate",
            fields=[
                (
                    "template_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "template_content",
                    models.TextField(help_text="Jinja2 template content"),
                ),
                ("template_file_path", models.CharField(blank=True, max_length=500)),
                ("version", models.CharField(default="1.0", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "form_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="issuers.secformtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "SEC Document Template",
                "verbose_name_plural": "SEC Document Templates",
                "db_table": "sec_document_templates",
                "ordering": ["-is_default", "form_type", "version"],
            },
        ),
        migrations.CreateModel(
            name="MappingPreset",
            fields=[
                (
                    "preset_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "offering_types_json",
                    models.JSONField(
                        blank=True, default=list, help_text="e.g., ['REG_D', 'REG_A']"
                    ),
                ),
                (
                    "mapping_config",
                    models.JSONField(help_text="Complete mapping configuration"),
                ),
                ("times_applied", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "form_types",
                    models.ManyToManyField(blank=True, to="issuers.secformtype"),
                ),
            ],
            options={
                "verbose_name": "Mapping Preset",
                "verbose_name_plural": "Mapping Presets",
                "db_table": "sec_mapping_presets",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="FieldMappingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "template_variable",
                    models.CharField(help_text="e.g., 'issuer_name'", max_length=200),
                ),
                (
                    "transformation_type",
                    models.CharField(
                        choices=[
                            ("DIRECT", "Direct Mapping"),
                            ("EXPRESSION", "Expression/Formula"),
                            ("CONCATENATE", "Concatenate Multiple Fields"),
                            ("LOOKUP", "Lookup Table"),
                            ("CONDITIONAL", "Conditional Logic"),
                            ("FUNCTION", "Custom Function"),
                        ],
                        default="DIRECT",
                        max_length=20,
                    ),
                ),
                ("transformation_expression", models.TextField(blank=True)),
                ("conditions", models.JSONField(blank=True, default=dict)),
                ("fallback_value", models.CharField(blank=True, max_length=500)),
                ("apply_formatting", models.BooleanField(default=True)),
                ("custom_format", models.CharField(blank=True, max_length=255)),
                ("priority", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fallback_field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fallback_mappings",
                        to="issuers.fielddefinition",
                    ),
                ),
                (
                    "source_field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mapping_rules",
                        to="issuers.fielddefinition",
                    ),
                ),
                (
                    "source_fields",
                    models.ManyToManyField(
                        blank=True,
                        related_name="multi_mapping_rules",
                        to="issuers.fielddefinition",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mapping_rules",
                        to="issuers.secdocumenttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Mapping Rule",
                "verbose_name_plural": "Field Mapping Rules",
                "db_table": "sec_field_mapping_rules",
                "ordering": ["-priority", "template", "template_variable"],
                "unique_together": {("template", "template_variable", "priority")},
            },
        ),
    ]
